The structure and format of this is provided by Neural Data Science: A primer in Python and Matplotlib. This lesson in particular starts in Chapter 2: 0.00 to 0.01

In [1]:
import numpy as np

# Modeling the nervous system of Caenorhabditis elegans
C.elegans has a nervous system composed of 302 neurons divided into seven different classes. Here we pretend that C.elegans neurons produces action potentials and that they are easily classified. Here we have two arrays with each respective position corresponding to a given type of neuron's typical firing rate, and how many neurons of each type there are. The inner dot product gives us the expected spike count of each neuron, and sums up the total spike count from the entire system.

In [3]:
neuralFiringRates = np.array([0.5, 1, 2, 4 ,8, 0.25, 3])
numberofneurons = np.array([45, 15, 35, 20, 50, 36, 101])
expectedSpikeCount = np.inner(neuralFiringRates,numberofneurons)
expectedSpikeCount

899.5

In [4]:
sum(numberofneurons) 

302

here we can see the sum of spikecounts or actions potentials per type of neuron by performing a simple multiplication between the neuralFiringRates and numberofneurons 

In [5]:
neuralFiringRates * numberofneurons

array([ 22.5,  15. ,  70. ,  80. , 400. ,   9. , 303. ])

The matrix multiplication is not commutative, so A*B is not B*A. One represents the inner (or Dot) product, the other the outer product (referred to as the "tensor product".

In [7]:
spikeCountCrossComparison = np.outer(neuralFiringRates, numberofneurons)
spikeCountCrossComparison

array([[ 22.5 ,   7.5 ,  17.5 ,  10.  ,  25.  ,  18.  ,  50.5 ],
       [ 45.  ,  15.  ,  35.  ,  20.  ,  50.  ,  36.  , 101.  ],
       [ 90.  ,  30.  ,  70.  ,  40.  , 100.  ,  72.  , 202.  ],
       [180.  ,  60.  , 140.  ,  80.  , 200.  , 144.  , 404.  ],
       [360.  , 120.  , 280.  , 160.  , 400.  , 288.  , 808.  ],
       [ 11.25,   3.75,   8.75,   5.  ,  12.5 ,   9.  ,  25.25],
       [135.  ,  45.  , 105.  ,  60.  , 150.  , 108.  , 303.  ]])

The above 7X7 table gives contains the full crooss of all possible firing rates times all possible neuron groups.

# Utility of using the Outer Dot product

To demonstrate why finding the various firing rates across neurons, the book dives into an example using the visual nervous system of simple organisms. In this experiment you want to use five exposure durations and five light levels, fully crossed. The outer proudct of exposure durations and light levels yields the total photon count that the organism is exposed to per condition.

In [8]:
exposureDurations = np.array([1,2,3,4,5])
lightLevels = np.array([1,2,4,8,16])
photonCounts = np.outer(exposureDurations,lightLevels)
photonCounts

array([[ 1,  2,  4,  8, 16],
       [ 2,  4,  8, 16, 32],
       [ 3,  6, 12, 24, 48],
       [ 4,  8, 16, 32, 64],
       [ 5, 10, 20, 40, 80]])

# The Find Function 

For say you are only interested in neurons that fire at a rate of more than three spikes per second. We first find the neuron classes that meet the condition, then their corresponding numbers and add them up. This allows us to find the number of nuerons that meet our conditions. 


In [9]:
indices = np.where(neuralFiringRates > 3)
indices

(array([3, 4], dtype=int64),)

In [10]:
neuronsMeetingConditions = np.sum(numberofneurons[indices])
neuronsMeetingConditions

70